name: myapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

# The version number for your application.
version: 1.0.0+1

# Specify the minimum Flutter SDK version.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  plaid_flutter: ^4.1.1
  jwt_decoder: ^2.0.1
  webview_flutter: ^4.10.0
  shared_preferences: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configuration.
flutter:
  uses-material-design: true

  # Specify assets to include in the app.
  assets:
    - assets/.env
